
jekyll:
  image: jekyll/jekyll
  container_name: jekyll_robgrzel.github.io
  command: jekyll s --config _config.yml, config.dev.yml --force_polling --incremental
  ports:
    - 4000:4000
  environment:
    - JEKYLL_ENV=dev
  volumes:
    - .:/srv/jekyll